language: java
script:
 - mvn test
 - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
jdk:
 - oraclejdk8
deploy:
 provider: heroku
 api-key: 
  secure: $HEROKU_API_KEY
 app: sgos
